import estafeta as es

def povoa_estafetas(health_planet):
    e1=es.Estafeta("Joao",1,False)
    health_planet.add_estafeta(e1.id,e1)
    e2=es.Estafeta("Maria",3,True)
    health_planet.add_estafeta(e2.id,e2)
    e3=es.Estafeta("Miguel",2,True)
    health_planet.add_estafeta(e3.id,e3)
    e4=es.Estafeta("Catia",1,False)
    health_planet.add_estafeta(e4.id,e4)
    e5=es.Estafeta("Ricardo",2,False)
    health_planet.add_estafeta(e5.id,e5)
    e6=es.Estafeta("Marta",2,False)
    health_planet.add_estafeta(e6.id,e6)
    e7=es.Estafeta("Rita",3,False)
    health_planet.add_estafeta(e7.id,e7)
    e8=es.Estafeta("Bruno",3,True)
    health_planet.add_estafeta(e8.id,e8)
    e9=es.Estafeta("Henrique",1,True)
    health_planet.add_estafeta(e9.id,e9)
    e10=es.Estafeta("Manuel",3,False)
    health_planet.add_estafeta(e10.id,e10)
    e11=es.Estafeta("Ema",1,False)
    health_planet.add_estafeta(e11.id,e11)